#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9806e_dsi_vdo_hlt_fwvga_ivo_ips_d5028_longteng.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
