#
# Makefile for misc devices that really don't fit anywhere else.
#

custom_kernel_flashlight := $(addsuffix /, $(shell echo $(CONFIG_CUSTOM_KERNEL_FLASHLIGHT)))
obj-y += $(custom_kernel_flashlight)



